// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFFUoOppY7L8esMJ7TDGTnBQzWgG8zGY',
    appId: '1:669179688158:web:8c7ed530adb4f523483e4f',
    messagingSenderId: '669179688158',
    projectId: 'occupier-f49d0',
    authDomain: 'occupier-f49d0.firebaseapp.com',
    storageBucket: 'occupier-f49d0.firebasestorage.app',
    measurementId: 'G-GLYXGTP4C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6gteDUwtVD4KnYz1xvhdp_Fmjn2qDmI',
    appId: '1:669179688158:android:390c70867368b98e483e4f',
    messagingSenderId: '669179688158',
    projectId: 'occupier-f49d0',
    storageBucket: 'occupier-f49d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDceedZfJU31uxd9vL9hgNgCQED_3pQ8ME',
    appId: '1:669179688158:ios:b4a95e8da1eb2342483e4f',
    messagingSenderId: '669179688158',
    projectId: 'occupier-f49d0',
    storageBucket: 'occupier-f49d0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDceedZfJU31uxd9vL9hgNgCQED_3pQ8ME',
    appId: '1:669179688158:ios:b4a95e8da1eb2342483e4f',
    messagingSenderId: '669179688158',
    projectId: 'occupier-f49d0',
    storageBucket: 'occupier-f49d0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgFFUoOppY7L8esMJ7TDGTnBQzWgG8zGY',
    appId: '1:669179688158:web:2ebd34b8d81d5f58483e4f',
    messagingSenderId: '669179688158',
    projectId: 'occupier-f49d0',
    authDomain: 'occupier-f49d0.firebaseapp.com',
    storageBucket: 'occupier-f49d0.firebasestorage.app',
    measurementId: 'G-HD19VD8CC8',
  );
}
